language: php

dist: trusty

sudo: false

addons:
  apt_packages:
    - enchant

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.4
  - nightly

env:
  global:
    - TEST_COMMAND="composer test"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - travis_retry composer install ${COMPOSER_FLAGS}

script:
  - $TEST_COMMAND
